version: "3.8"

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
services:
  api:
    container_name: api
    build:
      context: ./
      target: development
    env_file:
      - ./.env
    command: npm run dev
    ports:
      - 1337:1337
    volumes:
      - ./src:/usr/src/app/src

  pizza-pg:
    container_name: pizza-pg
    image: bitnami/postgresql
    ports:
      - ${POSTGRESSQL_PORT}:${POSTGRESSQL_PORT}
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}"]
      interval: 2s
      timeout: 2s
      retries: 50
